--- # Install Python and upgrade and update packages

- name: Update apt and install python
  hosts: raspberry_meteo
  gather_facts: no
  pre_tasks:
    - name: Update apt
      raw: apt-get update -y
    - name: Upgrade apt
      raw: apt-get upgrade -y
    - name: Install python and pip
      raw: "apt-get install {{ item }} -y"
      with_items:
        - python3
        - python3-pip
        - python3-setuptools
        - python3-dev
    - name: Update pip
      raw: pip3 install -U pip
