raspberry_meteo ansible_host=192.168.1.112 ansible_user=meteo ansible_ssh_private_key_file=/home/instodramat/.ssh/id_rsa ansible_become=yes become_flags="-E -S -n" become_method="sudo" env_path="/home/meteo/.profile"
